### ISSUE TITLE
BTC payment not in wallet

### ISSUE THREAD

**Issue by CreatrixX** [UnleashedChat/unleashed-sdk#1]
Hi - I topped up my account with some BTC a while ago and it does not appear in my account. Can you help me resolve this please? thx

**Comment by siim-m** [comment]
Can you send more details like username/email, time and amount of transaction via the `Report Issue` button in chat view? We'll add a better way to report issues like this in the near future.

<img width="546" alt="image" src="https://github.com/UnleashedChat/unleashed-sdk/assets/46551195/c95fcdf5-8d58-448b-8427-38e9e6d1a9ee">

**Comment by CreatrixX** [comment]
ok - just sent the details. I didn't know about the Hello feature, so couldn't figure out how to connect. Will someone follow up with me? If so, where would I look for the reply?

**Comment by siim-m** [comment]
Found a payment that was missed due to some issues we were having at the time. Your account has been credited now. If you have any more questions please send another message on the site and include an email address so we can communicate back directly.

> I didn't know about the Hello feature, so couldn't figure out how to connect

It's really meant for reporting chat-related issues. We'll be adding a more generic contact option.

**Comment by CreatrixX** [comment]
thanks so much!
